### PR TITLE
Fix for issue #37

### PR DESCRIPTION
**Pull request by tarassh**
This is fix for https://github.com/EOSIO/eosjs-ecc/issues/37

### CODE REVIEW

**Comment by qiushaoxi** [comment]
it is needed

**Comment by fengluo** [comment]
I also found this bug. It needs to be merged. @jcalfee

**Comment by jcalfee** [comment]
@fengluo thanks, I'll bring this to b1's attention..

**Comment by c0d3ster** [comment]
This is in fact a bug; I'll go ahead and merge this in now.  Thanks for the contribution.

**Comment by ajose01** [comment]
Do we know when this is making it to a release?

**Pull request merged**
